% Data_Analytics.m
% This script reads data from the CSV file generated by saveDataToCSV,


% Define the filename
filename = 'test_data4.csv';

% Check if the file exists
if ~isfile(filename)
    error(['File ', filename, ' does not exist. Please ensure data has been saved using saveDataToCSV.']);
end

% Read the data
data = readtable(filename);

% Define the LCOM columns and check if they exist
lcom_columns = {'LCOM_1', 'LCOM_2', 'LCOM_3', 'LCOM_4', 'LCOM_5'};
missing_lcom_columns = setdiff(lcom_columns, data.Properties.VariableNames);
if ~isempty(missing_lcom_columns)
    error(['The following LCOM columns are missing in the data file: ', strjoin(missing_lcom_columns, ', ')]);
end

% Define columns to compare against LCOM values for plotting
comparison_columns = {'PPA_Price_EUR_MWh', 'InterestRate', 'BioMethaneFeedPrice'}; % Example configuration columns

% Ensure selected columns exist in data
missing_columns = setdiff(comparison_columns, data.Properties.VariableNames);
if ~isempty(missing_columns)
    error(['The following comparison columns are missing in the data file: ', strjoin(missing_columns, ', ')]);
end

% Plot each comparison column against LCOM values
for i = 1:numel(comparison_columns)
    % Create a new figure for each comparison column
    figure;
    hold on;
    
    % Plot each LCOM column against the current comparison column
    for j = 1:numel(lcom_columns)
        plot(data.(comparison_columns{i}), data.(lcom_columns{j}), '-o', 'DisplayName', lcom_columns{j});
    end
    
    % Configure plot labels, title, and legend
    xlabel(comparison_columns{i});
    ylabel('LCOM');
    title(['LCOM vs ', comparison_columns{i}]);
    legend('show');
    grid on;
    hold off;
end

disp('Data analytics completed.');